
-- -----------------------------------------------------
-- Schema WORLD_ANIMALS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WORLD_ANIMALS` DEFAULT CHARACTER SET utf8 ;
USE `WORLD_ANIMALS` ;

-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`ESPECIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`ESPECIE` (
  `ID_ESPECIE` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(30) NOT NULL,
  `CARACTERISTICA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESPECIE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`ANIMAL` (
  `ID_ANIMAL` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `CARACTERISTICA` VARCHAR(255) NULL,
  `DOMESTICO` TINYINT NOT NULL,
  `ID_ESPECIE` INT NOT NULL,
  `EDAD` INT NULL,
  PRIMARY KEY (`ID_ANIMAL`),
  INDEX `fk_ANIMAL_ESPECIE_idx` (`ID_ESPECIE` ASC),
  CONSTRAINT `fk_ANIMAL_ESPECIE`
    FOREIGN KEY (`ID_ESPECIE`)
    REFERENCES `WORLD_ANIMALS`.`ESPECIE` (`ID_ESPECIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`RAZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`RAZA` (
  `ID_RAZA` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `COLOR` VARCHAR(45) NULL,
  `CARACTERISTICA` VARCHAR(45) NULL,
  `PAIS` VARCHAR(45) NULL,
  `ID_ANIMAL` INT NOT NULL,
  PRIMARY KEY (`ID_RAZA`),
  INDEX `fk_RAZA_ANIMAL1_idx` (`ID_ANIMAL` ASC),
  CONSTRAINT `fk_RAZA_ANIMAL1`
    FOREIGN KEY (`ID_ANIMAL`)
    REFERENCES `WORLD_ANIMALS`.`ANIMAL` (`ID_ANIMAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`CONTINENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`CONTINENTE` (
  `ID_CONTINENTE` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `ZONA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_CONTINENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`PAIS` (
  `ID_PAIS` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `NUM_HAB` INT NULL,
  `CAPITAL` VARCHAR(45) NOT NULL,
  `ID_CONTINENTE` INT NOT NULL,
  INDEX `fk_PAIS_CONTINENTE1_idx` (`ID_CONTINENTE` ASC),
  PRIMARY KEY (`ID_PAIS`),
  CONSTRAINT `fk_PAIS_CONTINENTE1`
    FOREIGN KEY (`ID_CONTINENTE`)
    REFERENCES `WORLD_ANIMALS`.`CONTINENTE` (`ID_CONTINENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`CONTINENTE_ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`CONTINENTE_ANIMAL` (
  `CONTINENTE_ID_CONTINENTE` INT NOT NULL ,
  `ID_ANIMAL` INT NOT NULL,
  PRIMARY KEY (`CONTINENTE_ID_CONTINENTE`, `ID_ANIMAL`),
  INDEX `fk_CONTINENTE_has_ANIMAL_ANIMAL1_idx` (`ID_ANIMAL` ASC),
  INDEX `fk_CONTINENTE_has_ANIMAL_CONTINENTE1_idx` (`CONTINENTE_ID_CONTINENTE` ASC),
  CONSTRAINT `fk_CONTINENTE_has_ANIMAL_CONTINENTE1`
    FOREIGN KEY (`CONTINENTE_ID_CONTINENTE`)
    REFERENCES `WORLD_ANIMALS`.`CONTINENTE` (`ID_CONTINENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTINENTE_has_ANIMAL_ANIMAL1`
    FOREIGN KEY (`ID_ANIMAL`)
    REFERENCES `WORLD_ANIMALS`.`ANIMAL` (`ID_ANIMAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WORLD_ANIMALS`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORLD_ANIMALS`.`PERSONA` (
  `ID_PERSONA` INT NOT NULL AUTO_INCREMENT,
  `SEXO` VARCHAR(45) NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `EDAD` INT NULL,
  `ID_PAIS` INT NOT NULL,
  PRIMARY KEY (`ID_PERSONA`),
  INDEX `fk_PERSONA_PAIS1_idx` (`ID_PAIS` ASC),
  CONSTRAINT `fk_PERSONA_PAIS1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `WORLD_ANIMALS`.`PAIS` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
