
INSERT INTO continente VALUES(1,'AFRICA','ECUADOR Y ZONA TEMPLADA');
INSERT INTO continente VALUES(2,'AMERICA','ECUADOR Y HEMISFERIO NORTE Y SUR');
INSERT INTO continente VALUES(3,'ANTARTIDA','HEMISFERIO SUR, ZONA CONGELADA');
INSERT INTO continente VALUES(4,'ASIA','HEMISFERIO NORTE');
INSERT INTO continente VALUES(5,'EUROPA','HEMISFERIO NORTE, ZONA TEMPLADA Y FRIA');
INSERT INTO continente VALUES(6,'OCEANIA','HEMISFERIO SUR');