
/*
INSERCIÓN DE LOS DATOS, ALTER TABLE Y MODIFICACIONES
*/

-- ----------------------------------------------------------------
-- CREACION ESPECIES
-- ----------------------------------------------------------------

-- SE MODIFICA EL TAMAÑO DE LA COLUMNA CARACTERISTICA
ALTER TABLE ESPECIE 
CHANGE COLUMN CARACTERISTICA `CARACTERISTICA` VARCHAR(90) NOT NULL ;

ALTER TABLE ESPECIE 
CHANGE COLUMN `NOMBRE` `ESPECIE_NOMBRE` VARCHAR(30) NOT NULL ;

INSERT INTO ESPECIE VALUES(1,'MAMIFERO','ANIMALES VERTEBRADOS, ALIMENTADOS POR SUS MADRES');
INSERT INTO ESPECIE VALUES(2,'AVE','VERTEBRADOS CON ALAS');
INSERT INTO ESPECIE VALUES(3,'PEZ','ANIMALES DE AGUA, VERTEBRADOS');
INSERT INTO ESPECIE VALUES(4,'REPTIL','INVERTEBRADOS SIN PATAS');
INSERT INTO ESPECIE VALUES(5,'ANFIBIO','ANIMALES INVERTEBRADOS DE ORIGEN MARINO');
INSERT INTO ESPECIE VALUES(6,'INSECTO',' BICHOS PEQUEÑOS INVERTEBRADOS');


-- ----------------------------------------------------------------
-- CREACION DE ANIMALES
-- ----------------------------------------------------------------
-- SE REFACTORIZA EL NOMBRE DE LA COLUMNA CARACTERISTICA POR PROPIEDAD
ALTER TABLE ANIMAL 
CHANGE COLUMN CARACTERISTICA PROPIEDAD VARCHAR(255) NULL DEFAULT NULL ;

-- SE REFACTORIZA EL NOMBRE DE LA COLUMNA VIDA POR EDAD MEDIA
ALTER TABLE ANIMAL 
CHANGE COLUMN EDAD VIDA_MEDIA INT NULL DEFAULT NULL ;

INSERT INTO ANIMAL VALUES(1,'PERRO','ANIMAL DE 4 PATAS, SE SUELE USAR COMO ANIMAL DE COMPAÑIA',1,15,1);
INSERT INTO ANIMAL VALUES(2,'GATO','ANIMAL DE 4 PATAS, FELINO DE CARACTER DOMINANTE',1,15,1);
INSERT INTO ANIMAL VALUES(3,'TIBURON','REY MARINO, ANIMAL CARNÍVOR Y PELIGROSO',0,50,3);
INSERT INTO ANIMAL VALUES(4,'BUITRE','PÁJARO CARROÑERO, SE ALIMENTA DE LA CARROÑA',0,20,2);
INSERT INTO ANIMAL VALUES(5,'PAJARO','AVE HERBÍVORA, SUELE VIVIR EN LIBERTAD, AUNQUE ES UN ANIMAL DOMÉSTICO',1,4,2);



-- ----------------------------------------------------------------
-- CREACION DE RAZA
-- ----------------------------------------------------------------

-- ----------------------------------------------------------------
-- CREACION DE LOS CONTINENTES
-- ----------------------------------------------------------------
INSERT INTO continente VALUES(1,'AFRICA','ECUADOR Y ZONA TEMPLADA');
INSERT INTO continente VALUES(2,'AMERICA','ECUADOR Y HEMISFERIO NORTE Y SUR');
INSERT INTO continente VALUES(3,'ANTARTIDA','HEMISFERIO SUR, ZONA CONGELADA');
INSERT INTO continente VALUES(4,'ASIA','HEMISFERIO NORTE');
INSERT INTO continente VALUES(5,'EUROPA','HEMISFERIO NORTE, ZONA TEMPLADA Y FRIA');
INSERT INTO continente VALUES(6,'OCEANIA','HEMISFERIO SUR');

-- ---------------------------------------------------------------
-- CREACION DE LOS PAISES
-- ---------------------------------------------------------------

-- PAISES AFRICA
INSERT INTO PAIS VALUES(189,'COSTA DE MARFIL',24300000,'YAMUSUKRU',1);
INSERT INTO PAIS VALUES(120,'CAMERUN',23500000,'YAUNDÈ',1);
INSERT INTO PAIS VALUES(288,'GHANA',28000000,'ACRA',1);
INSERT INTO PAIS VALUES(466,'MALÍ',19000000,'BAMAKO',1);
INSERT INTO PAIS VALUES(504,'MARRUECOS',34300000,'RABAT',1);
INSERT INTO PAIS VALUES(566,'NIGERIA',191200000,'ABUYA',1);
INSERT INTO PAIS VALUES(686,'SENEGAL',15000000,'DAKAR',1);

-- PAISES AMERICA
INSERT INTO PAIS VALUES(76,'BRASIL',210000000,'BRASILIA',2);
INSERT INTO PAIS VALUES(124,'CANADA',37346000,'OTTAWA',2);
INSERT INTO PAIS VALUES(170,'COLOMBIA',80720000,'BOGOTA',2);
INSERT INTO PAIS VALUES(840,'ESTADOS UNIDOS',329000000,'WASHINGTON',2);
INSERT INTO PAIS VALUES(484,'MEXICO',125000000,'CIUDAD DE MEXICO',2);
INSERT INTO PAIS VALUES(32,'ARGENTINA',44500000,'BUENOS AIRES',2);
INSERT INTO PAIS VALUES(68,'BOLIVIA',12000000,'SUCRE',2);
INSERT INTO PAIS VALUES(192,'CUBA',11200000,'LA HABANA',2);
INSERT INTO PAIS VALUES(188,'COSTA RICA',5000000,'SAN JOSE',2);
INSERT INTO PAIS VALUES(218,'ECUADOR',17700000,'QUITO',2);
INSERT INTO PAIS VALUES(332,'HAITI',11200000,'PUERTO PRINCIPE',2);
INSERT INTO PAIS VALUES(152,'CHILE',18800000,'SANTIAGO DE CHILE',2);

-- PAISES ASIA
INSERT INTO PAIS VALUES(156,'CHINA',1405000000,'PEKIN',4);
INSERT INTO PAIS VALUES(356,'INDIA',1398000000,'NUEVA DELHI',4);
INSERT INTO PAIS VALUES(360,'INDONESIA',269720000,'YAKARTA',4);
INSERT INTO PAIS VALUES(900,'RUSIA',146000000,'MOSCU',4);
INSERT INTO PAIS VALUES(392,'JAPON',12600000,'TOKIO',4);
INSERT INTO PAIS VALUES(608,'FILIPINAS',113000000,'MANILA',4);
INSERT INTO PAIS VALUES(50,'BANGLADESH',109000000,'DACA',4);

-- PAISES EUROPEOS
INSERT INTO PAIS VALUES(724,'ESPAÑA',48560000,'MADRID',5);
INSERT INTO PAIS VALUES(250,'FRANCIA',48560000,'PARIS',5);
INSERT INTO PAIS VALUES(276,'ALEMANIA',80720000,'BERLIN',5);
INSERT INTO PAIS VALUES(56,'BELGICA',11410000,'BRUSELA',5);
INSERT INTO PAIS VALUES(20,'ANDORRA',85000,'ANDORRA LA VIEJA',5);
INSERT INTO PAIS VALUES(246,'FINLANDIA',5500000,'HELSINKI',5);
INSERT INTO PAIS VALUES(300,'GRECIA',11410000,'ATENAS',5);
INSERT INTO PAIS VALUES(380,'ITALIA',11410000,'ROMA',5);
INSERT INTO PAIS VALUES(620,'PORTUGAL',10800000,'LISBOA',5);

-- PAISES OCEANIA
INSERT INTO PAIS VALUES(36,'AUSTRALIA',25150000,'CAMBERRA',6);
INSERT INTO PAIS VALUES(584,'ISLA MARSHALL',56000,'MAJURO',6);
INSERT INTO PAIS VALUES(554,'NUEVA ZELANDA',4915000,'WELLINGTON',6);
INSERT INTO PAIS VALUES(882,'SAMOA',196000,'APIA',6);


-- ----------------------------------------------------------------
-- CREACION DE PERSONA
-- ----------------------------------------------------------------
